1.change the construtor error.
2.using BLAS to conquer this error:  liblapack.so: undefined reference to symbol 'dgemm_'

according to https://code.google.com/p/m-a-d-n-e-s-s/issues/detail?id=46
CBLAS, which is a library that provides a C interface for BLAS functions, is not required by MADNESS. Try using "-lblas" (without the quotes) instead of "-lcblas."